---
- name: Deploy wg0.conf
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: "0600"
  notify: restart wireguard

- name: Enable and start wg-quick@wg0
  ansible.builtin.service:
    name: wg-quick@wg0
    enabled: true
    state: started
